name: Class-Handle
version: 1.04
abstract: Introspection-handle objects for classes
author: Adam Kennedy <cpan@ali.as>
license: unknown
distribution_type: module
build_requires:
  File::Spec: 0.80
  Test::More: 0.47
requires:
  perl: 5.005
  Class::ISA: 0
  Class::Inspector: 1.12
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
